version: "0.1"
name: cloud-playground
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - "POSTGRES_USER=development"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  rabbitmq:
    container_name: rabbitmq
    hostname: my-rabbit
    image: rabbitmq:3-management
    environment:
      - "RABBITMQ_DEFAULT_USER=development"
      - "RABBITMQ_DEFAULT_PASS=mysecretpassword"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
volumes:
  rabbitmq_data:
  postgres_data: